### ISSUE TITLE
Typo: "Uplodaed stats"

### ISSUE THREAD

**Issue by bradley-holt** [IBM-Bluemix/cf-deployment-tracker-client-node#2]
There is a typo in the log output: "Uplodaed stats" should be "Uploaded stats"

**Comment by germanattanasio** [comment]
I wrote a [PR:1](https://github.com/IBM-Bluemix/cf-deployment-tracker-client-node/pull/1) which fixes this issue.

**Comment by JakePeyser** [comment]
German's PR fixed this typo
